import '@madre/shared/main.scss';

import type { Metadata } from 'next';
import Link from 'next/link';

import { ThemeScript } from './components/scripts/ThemeScript';
import styles from './layout.module.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ThemeScript />
      </head>
      <body>
        <div className={styles.container}>
          <nav className={styles.nav}>
            <Link className={styles['brand-link']} href="/">
              Madre
            </Link>
            <div>오른쪽</div>
          </nav>
          <main className={styles.main}>main{children}</main>
        </div>
      </body>
    </html>
  );
}
