import '@madre/shared/main.scss';

import type { Metadata } from 'next';
import type { ReactNode } from 'react';

import { RootLayout as _RootLayout } from './components/layout/RootLayout';
import { RootThemeScript } from './components/scripts/RootThemeScript';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <head>
        <RootThemeScript />
      </head>
      <body>
        <_RootLayout>
          <_RootLayout.Header />
          <_RootLayout.Main>{children}</_RootLayout.Main>
        </_RootLayout>
      </body>
    </html>
  );
}
