version: "3.9"

services:
  madre-mysql:
    image: mysql:latest
    platform: linux/amd64
    container_name: madre-mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "${PWD}/mysql/data:/var/lib/mysql"
      - "${PWD}/mysql/log:/var/log/mysql"
      - "${PWD}/mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: madre
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul